skinparam handwritten false
skinparam actor {
    backgroundColor<<function>> Tan
    borderColor<<function>> DimGray

    backgroundColor<<person>> Pink
    borderColor<<person>> Black
}

skinparam node {
    backgroundColor<<platform>> LightSalmon
    borderColor<<platform>> Black
}

skinparam component {
    backgroundColor<<app>> LightBlue
    borderColor<<app>> Indigo
}


skinparam queue {
    backgroundColor<<esb>> Pink 
    borderColor<<esb>> Coral
}


