@startgantt

Project starts the 1 of january 2018

[Sharepoint Event Bridge] as [SEB] lasts 10 days

[DSuite Event Publisher] as [DEP]  lasts 10 days
[Brief Event Publisher] as [BEP]  lasts 10 days

[DSuite Document Converter]  as [DDC] lasts 10 days
[Item Metadata Management] as [IMM] lasts 10 days

[SEB] is colored in Coral/Green

[DEP] starts at [SEB]'s end
[BEP] starts at [DEP]'s end
[DDC] starts at [BEP]'s end
[IMM] starts at [BEP]'s end


@endgantt
@startgantt

Project starts the 1 of january 2018

[Asynchronous Mobile Replication] as [AMR] lasts 15 days

[Offline Viewer] as [OFF] lasts 25 days

[OFF] starts at [AMR]'s end

@endgantt
