@startsalt
{#
. | . | .
{
  Title
  ==
  Description
  --
  [View] | [Parent]
}{
  Title
  ==
  Description
  --
  [View] | [Parent]
}{
  Title
  ==
  Description
  --
  [View] | [Parent]
}
. | . | .
{
  Title
  ==
  Description
  --
  [View] | [Parent]
}{
  Title
  ==
  Description
  --
  [View] | [Parent]
}{
  Title
  ==
  Description
  --
  [View] | [Parent]
}
}
@endsalt