@startuml
!include ../../includes/theme.iuml
!include ../../includes/common.iuml!act_user

title Asynchronous Mobile Replication

frame "Network Domain" {

    !include ../../includes/common.iuml!svc_esb

    !include ../../includes/common.iuml!svc_mi
    !include ../../includes/common.iuml!svc_ad
    !include ../../includes/common.iuml!svc_vanguard

    !include ../../includes/common.iuml!svc_couch_proxy

    node "Couch DB Cluster" as CC {

        note "User DBs are created\nfor each user" as N1
        database "User Inbox" <<system>> as DB_IN
        database "User Outbox" <<system>> as DB_OUT
        N1 .up. DB_IN
        N1 .up. DB_OUT

        note "Internally Managed\nRoles for Couch\naccess managment" as N2
        database "User Roles" <<system>> as DB_ROLE 
        N2 .up. DB_ROLE
    }

}

CPNT_USER_AUTH .. SVC_AD
CPNT_USER_AUTH .. SVC_VANGUARD
CPNT_USER_AUTH .. DB_ROLE

SVC_MI .up. SVC_AD
SVC_MI .up. SVC_VANGUARD


ACT_USER .. SVC_COUCH_PROXY: HTTPS
CPNT_COUCH_PROXY -- DB_IN
CPNT_COUCH_PROXY -- DB_OUT
SVC_ESB <-down-> DB_IN
SVC_ESB <-down-> DB_OUT

@enduml
@startuml
!include ../../includes/theme.iuml

title Share Pack/Brief

partition "DSuite Collaboration" {
  (*) --> "Create/Modify Pack/Brief" 
  --> "Edit Distribution"
  --> === S1 ===
}

partition "DSuite AMR" {
  === S1 === --> "Add/Update Pack/Brief in AMR User Databases"
  --> === S2 ===
}

partition "DSuite Reader" {
  === S2 === --> "Synchronise changes"  
  --> === S3 ===
}

=== S1 === -down-> (*)
=== S2 === -down-> (*)
=== S3 === -down-> (*)

@enduml
@startuml
!include ../../includes/theme.iuml

title Unshare Pack/Brief

partition "DSuite Collaboration" {
  (*) --> "Edit Distribution"
  --> === S1 ===
}

partition "DSuite AMR" {
  === S1 === --> "Remove Brief from AMR User Databases"
  --> === S2 ===
}

partition "DSuite Reader" {
  === S2 === --> "Synchronise changes"    
  --> === S3 ===
}

=== S1 === -down-> (*)
=== S2 === -down-> (*)
=== S3 === -down-> (*)

@enduml

