@startuml
!include ../../includes/theme.iuml

title Document Conversion System

folder "Sharepoint" as SP {
    [Document Store] as doclib
    [Html Store] as htmllib
    !include ../../includes/common.iuml!svc_event_bridge
}

folder "App Server" as APP {

    !include ../../includes/common.iuml!svc_esb

    component "Brief Event Publisher" <<service>> as BEP

    !include ../../includes/common.iuml!svc_event_publisher
    !include ../../includes/common.iuml!svc_brief_converter

    [DSuite Document Conversion] as ADC
    [DSuite Document Item Metadata Management] as DIMM
    [Document Conversion] as DC
    database "Shared Store" as SQL


}


SVC_EVENT_BRIDGE ----> SVC_ESB

SVC_ESB <-up-> SVC_EVENT_PUBLISHER
SVC_ESB <-up-> BEP
SVC_ESB -up-> SVC_BRIEF_CONVERTER
SVC_ESB <-right-> ADC
SVC_ESB <-down-> DC
SVC_ESB -down-> DIMM

DC --> SQL
DIMM --> SQL


SVC_BRIEF_CONVERTER <-- doclib : GET
SVC_BRIEF_CONVERTER --> htmllib : PUT

@enduml
@startuml

!include ../../includes/theme.iuml

title SharePoint Event Bridge Activity

start


partition SharePoint {
    :Create/Modify\nPack/Brief;
}

partition "Event Bridge" {
    split
        :Item\nUpdating;
    split again
        :Item\nUpdated;
    end split
    :Item\nAdded;

}
stop
@enduml
@startuml

!include ../../includes/theme.iuml

title Event Publisher Activity

start
:Item\nAdded;

partition "Event Publisher" {

    split
        if (Is Existing Document) then
            -[#green]->
            :Publish\nItem Document\nChanged;
        else
            stop
        endif
    split again
        if (Is New Document) then
            -[#green]->
            :Publish\nItem \nCreated;

        else
            stop
        endif
    split again
        :Publish\nBrief Item\nChanged;

    end split


}

stop
@enduml
@startuml

!include ../../includes/theme.iuml

title Brief Document Changed Activity

start
:Publish\ Document\nChanged;

partition "Brief Event Publisher" {
    if (Is a Brief Event) then
        -[#green]->
        :Publish\nBrief Document\nChanged;
    else
        stop
    endif
}

stop
@enduml

@startuml

!include ../../includes/theme.iuml

title Brief Item Created Activity

start
:Publish\nItem\nCreated;

partition "Brief Event Publisher" {

    if (Is a Brief Event) then
        -[#green]->
        :Publish\nBrief Document\nCreated;
    else
        stop
    endif

}

partition "DSuite Document Item Metadata Management" {
    :Store\nBrief Metadata;
}

stop
@enduml
@startuml

!include ../../includes/theme.iuml

title Brief Item Changed Activity

start
:Publish\nItem\nChanged;

partition "Brief Event Publisher" {

    if (Is a Brief Event) then
        -[#green]->
        :Publish\nBrief Item\nChanged;
    else
        stop
    endif    
}

partition "DSuite Document Item Metadata Management" {
    :Store\nBrief Metadata;
}

stop
@enduml

@startuml

!include ../../includes/theme.iuml

title Brief Document Converter

start
:Publish\nBrief Document\nChanged;

partition "Brief Event Publisher" {

    if (Is a Brief Event) then
        -[#green]->
        :Convert SharePoint Hosted Document;
    else
        stop
    endif    
}

partition "DSuite Document Converter" {
    :Convert Document;
    :Reply;
}

stop
@enduml
