@startuml
!include ../includes/theme.iuml

title CouchDB

frame "Network Domain" {

    actor "Internal User" <<person>> as AU

    component [Active Directory] <<system>> as AD 
    component [Vanguard] <<system>> as VG

    component [Mobile Iron] <<system>> as MI 

    node "Proxy Service" as CPS {
        component "Authentication Manager" as AUTH 
        component "Couch Proxy" as CP 
    }

    queue "Event Bus" <<service>> as ESB


    node "Couch DB Cluster" as CC {

        database "User Inbox" <<system>> as DB_IN
        database "User Outbox" <<system>> as DB_OUT


        note "Internally Managed\nRoles for Couch\naccess managment" as N1
        database "User Roles" <<system>> as DB_ROLE 

    }

}

AUTH .. AD
AUTH .. VG
AUTH .. DB_ROLE

MI .up. AD
MI .up. VG

CP .right. AUTH
AU .. CP
CP -- DB_IN
CP -- DB_OUT
ESB <-down-> DB_IN
ESB <-down-> DB_OUT

N1 .up. DB_ROLE

@enduml