@startuml
left to right direction
!include ../../includes/theme.iuml
!include ../../includes/common.iuml!act_owner
!include ../../includes/common.iuml!act_editor

ACT_EDITOR <|-- ACT_OWNER: Can Do

ACT_OWNER .. (Create) : Uses
ACT_OWNER .. (Archive)  : Uses


@enduml