site_name: Digital Suite Technical Design
theme:
  name: 'material'
  logo:
    icon: 'lightbulb_outline'  
markdown_extensions:
  - meta
  - admonition  
  - footnotes
  - codehilite
  - toc:
      permalink: true      