skinparam handwritten false
skinparam actor {
    backgroundColor<<person>> Tan
    borderColor<<person>> DimGray
}

skinparam node {
    backgroundColor<<platform>> LightSalmon
    borderColor<<platform>> Black
}

skinparam component {
    backgroundColor<<app>> CornFlowerBlue
    borderColor<<app>> Indigo
}
