@startuml
title Hello Gulp!
actor Greg
actor Bob

Greg -> Bob: Authentication Request
Bob --> Greg: Authentication Response

Greg -> Bob: Another authentication Request
Greg <-- Bob: another authentication Response

@enduml