@startuml

cloud "DSuite" {

    node "Viewer" {

        component [Browser] as C_APP_BROWSER

        component [Offline] as C_APP_IOS

        database "PouchDb" as POUCH_DB 
    }

    node "SharePoint" as SP {
        folder "Site" {
            component [Document Library] as C_DOCUMENTLIB
            component [List] as C_SP_LIST
            component [Event Bridge] as C_EVENTBRIDGE
        }

       
    }

    node "Administration" {

        folder "Pack"  as APP_PACK {
            component [Pack] as C_APP_PACK
            component [Navigation] as C_APP_NAVIGATION
            component [Communication] as C_APP_COMMUNICATION
            component [Decisions] as C_APP_DECISION
        }

        folder "MetaData" as APP_META {
            component [Lists] as C_APP_LISTS
        }

        folder "Security"  as APP_SECURITY {
            component [Readers] as C_APP_USERS
            component [Roles] as C_APP_ROLES
            component [Operations] as C_APP_OPERATIONS
        }

        folder "Comms" as APP_COMMS {
            component [Notification] as C_APP_NOTIFICATION
            component [Distribution] as C_APP_DISTRIBUTION
        }

    }

    node "Couch DB" {
        database "Reader Inbox" as DB_USER_INBOX
        database "Reader Outbox" as DB_USER_OUTBOX
    } 

    node "Sql Server" {

        database "Pack" as DB_PACK
        database "Lists" as DB_LISTS
        database "Security" as DB_SECURITY

        database "Notification" as DB_NOTIFICATION
        database "Subscription" as DB_SUBSCRIPTION
        database "Securables" as DB_SECURABLES
    }


    node "Enterprise Service Bus" {
        
        folder "Replication (Offline)" {
            component [Pack to Securable] as EP_P2S
            component [Securable Distributor] as EP_SEC_DIST
            component [Couch Bridge] as EP_COUCHBRIDGE
        }

        folder "Platform Integration" {
            component [Event Publisher] as EP_EVENTPUBLISHER
            component [Document Conversion] as EP_DOCUMENT
            component [Pack Builder] as EP_PACK_BUILD
        }

        folder "Undefined Processing" as TBD {
            component [Some Process] as MYSTERY
        }
        
    }

}

APP_PACK ..down..> APP_META
APP_PACK ..down..> APP_SECURITY 
APP_PACK ..down..> APP_COMMS 

MYSTERY ..up..> APP_PACK
MYSTERY ..up..> SP

EP_EVENTPUBLISHER .up.> EP_DOCUMENT
EP_EVENTPUBLISHER ..up..> EP_PACK_BUILD

C_DOCUMENTLIB -down-> C_EVENTBRIDGE: SharePoint Event
C_SP_LIST -down-> C_EVENTBRIDGE

C_APP_BROWSER -up-> POUCH_DB: Uses
C_APP_IOS -up-> POUCH_DB: Uses

POUCH_DB <--up--> DB_USER_INBOX: Replicates
POUCH_DB <--up--> DB_USER_OUTBOX: Replicates

EP_COUCHBRIDGE <--down--> DB_USER_INBOX: Listens
EP_COUCHBRIDGE <--down--> DB_USER_OUTBOX: Listens

EP_COUCHBRIDGE ..right..> MYSTERY
C_EVENTBRIDGE .....>  EP_EVENTPUBLISHER : Domain Event

EP_DOCUMENT ..up..> DB_SECURABLES
EP_PACK_BUILD ..up..> DB_PACK

C_APP_PACK --down--> DB_PACK
C_APP_LISTS --down--> DB_LISTS

APP_SECURITY --down--> DB_SECURITY

C_APP_NOTIFICATION --down--> DB_NOTIFICATION
C_APP_DISTRIBUTION --down--> DB_SUBSCRIPTION

DB_PACK --down--> EP_P2S
EP_P2S --> DB_SECURABLES

DB_SECURABLES --down--> EP_SEC_DIST
EP_SEC_DIST --> DB_USER_INBOX

@enduml
