
@startuml

folder "Corporate Domain" as DOMAIN {

!include includes/common.iuml!sys_dsuite
!include includes/theme.iuml
!include includes/common.iuml!pla_sql
!include includes/common.iuml!pla_sp
!include includes/common.iuml!pla_couch
!include includes/common.iuml!pla_web
!include includes/common.iuml!svc_mi
!include includes/common.iuml!svc_esb

!include includes/common.iuml!act_user

node "Approved Device" as DEVICE {
    !include includes/common.iuml!app_ms_office
    !include includes/common.iuml!app_browser
    !include includes/common.iuml!app_email
}
note "Department issued\nlaptops and iPads" as N1

DEVICE .. N1
DEVICE .up. SVC_MI 
ACT_USER .. DEVICE 

APP_MS_OFFICE ... PLA_SP
APP_BROWSER ... PLA_WEB


SYS_DSUITE -up- PLA_SP : (HTTPS)
SYS_DSUITE -up- PLA_WEB : (TCP/IP)
SYS_DSUITE -right- SVC_ESB : (TCP/IP)
SYS_DSUITE -left- PLA_COUCH : (HTTPS)
SYS_DSUITE -down- PLA_SQL : (TCP/IP)



PLA_SP -- PLA_SQL : (TCP/IP) 

SVC_ESB -- PLA_COUCH : (HTTPS)
SVC_ESB -- PLA_SP : (TCP/IP)
SVC_ESB -- PLA_SQL : (TCP/IP)

}



@enduml